name:    maelstromHs
version: "0.0.1"

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- text

default-extensions:
- DeriveGeneric
- ImportQualifiedPost
- LambdaCase
- OverloadedRecordDot
- OverloadedStrings
- RecordWildCards
- TypeApplications

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  maelstromHs:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maelstromHs

# Test suite
tests:
  maelstromHs-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - maelstromHs
    - hspec
